# Generated by Django 5.0.6 on 2024-06-11 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_file_filename_file_filetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='filename',
        ),
    ]
